
sut:
  build: .
  command: bash run_test.sh
  ports:
    - 8083:8083
  links:
    - mongo

mongo:
  image: mongo
  container_name: springboot-mongo
  ports:
    - 27017:27017
  volumes:
    - ./data:/data/db
    - ./data_bkp:/data/bkp
  restart: always
