version: '2'

services:
  mongodb:
    container_name: some-mongo
    image: mongo:3.6
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
        - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  core:
    container_name: playground.sheena
    restart: always
    build: .
    command: /app/mvnw test -f /app/pom.xml
    depends_on:
      - mongodb