FROM openjdk:8-alpine

# Required for starting application up.
RUN apk update && apk add bash

RUN mkdir -p /opt/app
ENV PROJECT_HOME /opt/app

COPY . $PROJECT_HOME
WORKDIR $PROJECT_HOME

CMD ["bash", "run_test.sh"]