version: '3.1'

services:
  playground:
    build: .
    restart: always
    container_name: playground
    ports:
      - 8083:8083
    depends_on:
      - mongo
  
  mongo:
    image: mongo3.6
    container_name: playground-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./data_bkp:/data/bkp
    restart: always