version: '3.1'

services:
  core:
    build: .
    restart: always
    container_name: playground
    command: bash run_test.sh
    ports:
      - 8083:8083
    working_dir: /opt/app
    depends_on:
      - mongo
  
  mongo:
    image: mongo
    container_name: springboot-mongo
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
      - ./data_bkp:/data/bkp
    restart: always
  